/*
 * TIMER1_types.h
 *
 *  Created on: Mar 2, 2023
 *      Author: musta
 */

#ifndef TIMER1_TIMER1_TYPES_H_
#define TIMER1_TIMER1_TYPES_H_

typedef enum
{
	TIMER1_STOP = 0,        /*0b0000*/
	TIMER1_NO_PRESCALER,    /*0b0001*/
	TIMER1_PRESCALER_8,     /*0b0010*/
	TIMER1_PRESCALER_64,	/*0b0011*/
	TIMER1_PRESCALER_256,	/*0b0100*/
	TIMER1_PRESCALER_1024,	/*0b0101*/
	TIMER1_EXT_CLK_FALLING,	/*0b0110*/
	TIMER1_EXT_CLK_RISING	/*0b0111*/
}Timer1_Prescaler_Type;

typedef enum
{
	TIMER1_NORMAL_MODE = 0,
	TIMER1_CTC_OCRA_TOP_MODE = 4,
	TIMER1_CTC_ICR_TOP_MODE = 12,
	TIMER1_FASTPWM_FIXED_8BIT_MODE = 5,
	TIMER1_FASTPWM_ICR_TOP_MODE = 14,
	TIMER1_FASTPWM_OCRA_TOP_MODE = 15,
	TIMER1_PHASECORRECT_FIXED_8BIT_MODE = 1,
	TIMER1_PHASECORRECT_ICR_TOP_MODE = 10,
	TIMER1_PHASECORRECT_OCRA_TOP_MODE = 11,
	TIMER1_PHASEANDFREQCORRECT_ICR_TOP_MODE = 8,
	TIMER1_PHASEANDFREQCORRECT_OCRA_TOP_MODE = 9
}Timer1_Mode_Type;

typedef enum
{
	OC1A_DISCONNECT = 0,         /*0b0000*/
	OC1A_TOGGLE_NONPWM_MODES = 1,                 /*0b0001*/
	OC1A_CLEAR_NONPWM_MODES = 2,                  /*0b0010*/
	OC1A_SET_NONPWM_MODES = 3,                     /*0b0011*/
	OC1A_TOGGLE_FASTPWM_OCRA_TOP_MODE = 1,
	OC1A_NON_INVERTING_PWM_MODES = 2,
	OC1A_INVERTING_PWM_MODES = 3
}OC1A_Mode_type;

typedef enum
{
	OC1B_DISCONNECT = 0,         /*0b0000*/
	OC1B_TOGGLE_NONPWM_MODES = 1,                 /*0b0001*/
	OC1B_CLEAR_NONPWM_MODES = 2,                  /*0b0010*/
	OC1B_SET_NONPWM_MODES = 3,                     /*0b0011*/
	OC1B_NON_INVERTING_PWM_MODES = 2,
	OC1B_INVERTING_PWM_MODES = 3
}OC1B_Mode_type;

typedef enum
{
	ICU_FALLING = 0,
	ICU_RISING = 1
}ICU_Edge_type;

typedef enum
{
	TIMER1_OVF_INTERRUPT = 0,
	TIMER1_OCR_A_INTERRUPT,
	TIMER1_OCR_B_INTERRUPT,
	TIMER1_ICU_INTERRUPT
}Timer1InterruptSource_type;

#endif /* TIMER1_TIMER1_TYPES_H_ */
