/*
 * EXTI_priv.h
 *
 *  Created on: Feb 24, 2023
 *      Author: musta
 */

#ifndef EXTI_EXTI_PRIV_H_
#define EXTI_EXTI_PRIV_H_

#define EXTI_INT0_LOW_LEVEL_REQUEST				0
#define EXTI_INT0_LOGICAL_CHANGE_REQUEST		1
#define EXTI_INT0_FALLING_EDGE_REQUEST			2
#define EXTI_INT0_RISING_EDGE_REQUEST			3

#define EXTI_INT1_LOW_LEVEL_REQUEST				0
#define EXTI_INT1_LOGICAL_CHANGE_REQUEST		1
#define EXTI_INT1_FALLING_EDGE_REQUEST			2
#define EXTI_INT1_RISING_EDGE_REQUEST			3

#define EXTI_INT2_FALLING_EDGE_REQUEST			0
#define EXTI_INT2_RISING_EDGE_REQUEST			1

#endif /* EXTI_EXTI_PRIV_H_ */
