/*
 * TIMER0_types.h
 *
 *  Created on: Feb 25, 2023
 *      Author: musta
 */

#ifndef TIMER0_TIMER0_TYPES_H_
#define TIMER0_TIMER0_TYPES_H_

typedef enum
{
	TIMER0_NORMAL_MODE,
	TIMER0_CTC_MODE,
	TIMER0_PWM_PHASE_CORRECT_MODE = 0x08,
    TIMER0_FAST_PWM_MODE
}timer0_mode_config_t;

typedef enum
{
	TIMER0_COMPARE_OUTPUT_NON_PWM_NORMAL_MODE = 0,
	TIMER0_COMPARE_OUTPUT_NON_PWM_TOGGLE_MODE,
	TIMER0_COMPARE_OUTPUT_NON_PWM_CLEAR_MODE,
	TIMER0_COMPARE_OUTPUT_NON_PWM_SET_MODE,

	TIMER0_COMPARE_OUTPUT_FAST_PWM_NORMAL_MODE = 0,
	TIMER0_COMPARE_OUTPUT_FAST_PWM_CLEAR_MODE = 2,
	TIMER0_COMPARE_OUTPUT_FAST_PWM_SET_MODE,

	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_NORMAL_MODE = 0,
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_CLEAR_MODE = 2,
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_SET_MODE
}timer0_output_compare_mode_t;

typedef enum
{
	TIMER0_CLOCK_SELECT_NO_CLOCK,
	TIMER0_CLOCK_SELECT_IO_CLOCK,
	TIMER0_CLOCK_SELECT_IO_CLOCK_DIV_BY_8,
	TIMER0_CLOCK_SELECT_IO_CLOCK_DIV_BY_64,
	TIMER0_CLOCK_SELECT_IO_CLOCK_DIV_BY_256,
	TIMER0_CLOCK_SELECT_IO_CLOCK_DIV_BY_1024,
	TIMER0_CLOCK_SELECT_EXTERNAL_CLOCK_FALLING_EDGE,
	TIMER0_CLOCK_SELECT_EXTERNAL_CLOCK_RISING_EDGE
}timer0_prescaler_t;

typedef struct
{
	timer0_mode_config_t timer_mode;
	timer0_output_compare_mode_t oc_mode_configs;
	timer0_prescaler_t prescaler;
	u8 value_of_OCR0;
}timer0_config_t;
#endif /* TIMER0_TIMER0_TYPES_H_ */
